version: '3.8'
services:
  codex-container:
    container_name: codex_api
    env_file:
      - .env  # Path to your .env file
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8888:8000'
    command: npm run start:dev
    # restart: unless-stopped
    networks:
      - codex-networks

networks:
  codex-networks:
    name: 'codex-networks'
    external: true
